name: Deploy Backend Auth (Branch Deploy)

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

on:
  push:
    branches: [ "deploy" ]

jobs:
  ci-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # Actualizado a v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v5 # Actualizado a v5
        with:
          node-version: '22' # Node 22 es el estándar estable en 2026
          cache: 'npm'
      
      - run: npm install
      - run: npm run lint || echo "No lint found"
      - run: node --check src/index.js

  cd-deployment:
    needs: ci-validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-adopcion-backend-dev'
          package: .